### ISSUE TITLE
linkage and locations - navigations

### ISSUE THREAD

**Issue by theuxyeti** [theuxyeti/SugarSteem#2]
review this from busy.org and adjust the linkages to meet these within our navigation bar at the top. 
![linkage and locations](https://user-images.githubusercontent.com/36086326/37878762-c2ba5bfe-3022-11e8-9667-f8244f95bcd7.png)

**Comment by r351574nc3** [comment]
I notice there are links for mentions, replies, and comments. There are now issues or views for those. Do you plan on making them?

If you haven't yet, I wonder if you'd like to consider combining the 3. It always seemed a bit awkward to me that comments/replies were separated. I noticed that **chainbb** was/is really popular because it provides a threaded view of comments/replies (probably because it's a bbs. LOL.)

It might save some space in the interface to provide a thread-like view for comments/replies/mentions.

We also need views for Wallet and Links.

**Comment by theuxyeti** [comment]
I’m not changing the layout. It’s already been revised a number of times. Try loading the chrome extension more steem info and trying it out. I’d like to have that extension loaded into the ui

**Comment by theuxyeti** [comment]
This issue was moved to SugarSteem/SugarSteem#16
